language: python
python:
    - "3.8"

sudo: true
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U npm
    - pip install -U platformio
    - platformio update

script:
    - platformio run
